server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.kaikeba.bean
    configuration:
      lazy-loading-enabled: true
      aggressive-lazy-loading: false
